"""add provider order id

Revision ID: 6f7ae02e52c4
Revises: 2b0807fad076
Create Date: 2026-06-11 19:11:39.404824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f7ae02e52c4"
down_revision: Union[str, Sequence[str], None] = "2b0807fad076"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("provider_order_id", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "provider_order_id")
    # ### end Alembic commands ###
