"""add menu item fields

Revision ID: b1a2c3d4e5f6
Revises: 9cdf0a6885fe
Create Date: 2026-06-09 15:40:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b1a2c3d4e5f6"
down_revision: Union[str, Sequence[str], None] = "9cdf0a6885fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menu_items",
        sa.Column(
            "veg_type", sa.String(length=50), nullable=False, server_default="veg"
        ),
    )
    op.add_column(
        "menu_items",
        sa.Column(
            "preparation_time_minutes",
            sa.Integer(),
            nullable=False,
            server_default="10",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menu_items", "preparation_time_minutes")
    op.drop_column("menu_items", "veg_type")
    # ### end Alembic commands ###
