"""fix cart relationship

Revision ID: ee007ae7abea
Revises: 639dce88f478
Create Date: 2026-06-10 17:19:21.954107

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ee007ae7abea"
down_revision: Union[str, Sequence[str], None] = "639dce88f478"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
